name: deploy-flashcard-app-heroku # 1

on:
  push:
    branches: # 2
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # 3
      - run: npm ci # 4
      - name: Run production migration
        run: npm run migrate:deploy # 5
